### ISSUE TITLE
NullPointerException from getInterpolants

### ISSUE THREAD

**Issue by agacek** [ultimate-pa/smtinterpol#11] opened 2015-12-14 14:13 UTC
I'm getting the following trace SMTInterpol:
```
java.lang.NullPointerException
	at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.Interpolator.interpolate(Interpolator.java:457)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.interpolate.Interpolator.getInterpolants(Interpolator.java:263)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.getInterpolants(SMTInterpol.java:1220)
	at de.uni_freiburg.informatik.ultimate.logic.NoopScript.getInterpolants(NoopScript.java:230)
	at de.uni_freiburg.informatik.ultimate.logic.LoggingScript.getInterpolants(LoggingScript.java:327)
	at jkind.engines.pdr.PdrSmt.getInterpolants(PdrSmt.java:317)
	at jkind.engines.pdr.PdrSmt.refine(PdrSmt.java:295)
	at jkind.engines.pdr.PdrSubengine.blockCube(PdrSubengine.java:104)
	at jkind.engines.pdr.PdrSubengine.run(PdrSubengine.java:71)
```
This doesn't happened when I run the smt2 file that is being logged. It only happens when I go through the API. I'm not sure how to go about getting an smt2 file that exhibits the same behavior.

**Comment by agacek** [comment] 2015-12-14 22:36
I did a git bisect and it appears the problem was introduced in 9072cb4119ebabf43a1d5f8eeb4915a66aa1b47f.

**Comment by Pomrehn** [comment] 2015-12-15 12:43
Can you try this patch?
https://github.com/ultimate-pa/smtinterpol/compare/master...jhoenicke:master

I'm not sure which variable is null in your run.  Is it the engine?  I have no idea why. Do you do something between checkSat and getInterpolants?

**Comment by jhoenicke** [comment] 2015-12-15 12:47
Can you try this patch?
https://github.com/ultimate-pa/smtinterpol/compare/master...jhoenicke:master

I'm not sure which variable is null in your run.  Is it the engine?  I have no idea why. Do you do something between checkSat and getInterpolants?

**Comment by agacek** [comment] 2015-12-15 14:55
I still get the null pointer with that patch. It happens on the very first time I call getInterpolants. I'm calling checkSat right before it. Here's where I call it in my code:

  https://github.com/agacek/jkind/blob/master/jkind/src/jkind/engines/pdr/PdrSmt.java#L317

**Comment by agacek** [comment] 2015-12-15 15:13
Here's what I found from debugging:

mSmtSolver is initialized to null in the Interpolator constructor.

mInterpolantCheckMode is false in SMTInterpol::getInterpolants so tmpBench is null.

I don't get the null pointer if I turn on :interpolant-check-mode.

**Comment by jhoenicke** [comment] 2015-12-15 16:21
Ah, I see. mSmtSolver is null if interpolant-check-mode is turned off.  I updated the patch to always give a valid SMTInterpol reference to the interpolator in the constructor.

Can you try this again (same URL as above).

**Comment by agacek** [comment] 2015-12-15 17:03
With that patch I no longer get the null pointer exception. But now my code is failing in another place. The answer I'm getting back from the PDR engine I built on top of SMTInterpol is returning something that doesn't look right. I'll have to dig into the code more to see what's going wrong. But the issue goes away when :interpolant-check-mode is set to true. It seems strange that checking would change the answer.

**Comment by jhoenicke** [comment] 2015-12-15 17:19
Okay, this had more consequences than expected.  The interpolator uses mSmtSolver != null as a check if it should check interpolants.  Do you have Config.DEEP_CHECK_INTERPOLANTS enabled?

The problem is that if checkInterpolants is not enabled it still does the checks (because mSmtSolver != null now holds) but it does them on the same engine instead of a copy, which interferes with the normal operation.

As a work around, set DEEP_CHECK_INTERPOLANTS to false.  I will clean up the code later to check for InterpolantsCheckMode instead of just testing for != null.

**Comment by agacek** [comment] 2015-12-15 17:37
I don't think I have DEEP_CHECK_INTERPOLANTS enabled. Here's my configuration for the solver:

```
script.setOption(":produce-interpolants", true);
script.setOption(":produce-unsat-cores", true);
script.setOption(":simplify-interpolants", true);
// script.setOption(":interpolant-check-mode", true);
script.setLogic(Logics.QF_UFLIRA);
script.setOption(":verbosity", 2);
```

And in SMTInterpol I see that DEEP_CHECK_INTERPOLANTS is initialized to false.

**Comment by jhoenicke** [comment] 2016-01-06 13:52
Do you have a simple instruction how to run jkind and on which example to reproduce the bug.  It is hard to remotely debug the problem :)

**Comment by agacek** [comment] 2016-01-06 14:40
Sure, the input file to JKind is here:

https://gist.github.com/agacek/af61097b9ddeb2da777c

I run JKind with the flags

`-no_bmc -no_k_induction -no_inv_gen test.lus`

If you are running from the JKind sources you'll want to execute the Main.java file with the arguments

`-jkind -no_bmc -no_k_induction -no_inv_gen test.lus`

**Comment by stieglma** [comment] 2016-02-04 08:18
I just tried to integrate the newest version of SMTInterpol into java-smt and did also encounter this bug. Are there any plans to fix this in the near future or do we need to enable ```interpolant-check-mode```? At least our unit-tests would work with it, but I'm not sure if the extra runtime for this check is worth upgrading to this version.

**Comment by jhoenicke** [comment] 2016-02-04 15:09
I have cleaned up the previous patch and committed it to master.  Now the interpolator stores the two instances of SMTInterpol (one to check for timeout and one for the DEEP_CHECK_INTERPOLANTS mode) separately;  the first one is never null, the second is checked before being used.

This should fix the problem.  Can you confirm?

**Comment by agacek** [comment] 2016-02-04 15:33
I just tested the latest build of SMTInterpol from master. I no longer get the `NullPointerException`. Hopefully it resolves @stieglma's issue as well.

**Comment by stieglma** [comment] 2016-02-04 16:02
The change works for us, too. Thank you for the fast reply!

**Closed** 2016-02-04 16:07 UTC
